#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Configuration of the HAProxy
# Make sure that HAProxy can be managed via an init script
# Install and configure HAproxy on my lb-01 server.
# request diversife to web 01 and web 02
sudo apt-get -y update
sudo apt-get -y install haproxy

# edit config file
server_config=\
"
frontend  brian-frontend
        bind *:80
        mode http
        default_backend brian-backend
backend brian-backend
        balance roundrobin
        server 104302-web-01 54.236.24.125:80 check
        server 104302-web-02 100.25.136.163:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
